"""Migración inicial

Revision ID: 0fa4ac2504a5
Revises: cd0751087bbf
Create Date: 2025-06-19 21:34:43.624997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fa4ac2504a5'
down_revision = 'cd0751087bbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=120), nullable=False),
    sa.Column('fecha', sa.String(length=50), nullable=False),
    sa.Column('hora', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turno')
    # ### end Alembic commands ###
