"""Hacer campo usuario opcional en turnos

Revision ID: 9fc506c9ed63
Revises: inicial001
Create Date: 2025-06-20 16:25:45.603783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc506c9ed63'
down_revision = 'inicial001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cliente_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('servicio', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('precio', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('notas', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('usuario',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.create_foreign_key(None, 'clientes', ['cliente_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turnos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('usuario',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('notas')
        batch_op.drop_column('precio')
        batch_op.drop_column('servicio')
        batch_op.drop_column('cliente_id')

    # ### end Alembic commands ###
